version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
  db:
    image: postgres12
    environment:
      POSTGRES_DB: megano
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
